// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trab_AV2.Model.Models;

public partial class ItensVenda
{
    public int ItvCodigoVenda { get; set; }

    public int ItvCodigoProduto { get; set; }

    public int ItvCodigo { get; set; }

    public decimal ItvQuantidade { get; set; }

    public decimal ItvValorItem { get; set; }
}