// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Trab_AV2.Model.Models;

public partial class PADARIA_AV2Context : DbContext
{
    public PADARIA_AV2Context(DbContextOptions<PADARIA_AV2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Produto> Produtos { get; set; }

    public virtual DbSet<SimNao> SimNaos { get; set; }

    public virtual DbSet<Vendum> Venda { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Produto>(entity =>
        {
            entity.ToTable("PRODUTOS");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Disp).HasColumnName("DISP");
            entity.Property(e => e.IdUser)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("ID_USER");
            entity.Property(e => e.NmProduto)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("NM_PRODUTO");
            entity.Property(e => e.Qtd)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("QTD");
            entity.Property(e => e.Valor)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("VALOR");
        });

        modelBuilder.Entity<SimNao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SIM_NAO__3214EC278C446DF7");

            entity.ToTable("SIM_NAO");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("DESCRICAO");
        });

        modelBuilder.Entity<Vendum>(entity =>
        {
            entity.ToTable("VENDA");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.DataVenda)
                .HasColumnType("datetime")
                .HasColumnName("DATA_VENDA");
            entity.Property(e => e.IdProduto).HasColumnName("ID_PRODUTO");
            entity.Property(e => e.IdUser)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("ID_USER");
            entity.Property(e => e.ValorVenda)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("VALOR_VENDA");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}