// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trab_AV2.Model.Models;

public partial class Produto
{
    public int Id { get; set; }

    public string IdUser { get; set; }

    public string NmProduto { get; set; }

    public string Qtd { get; set; }

    public decimal Valor { get; set; }

    public int Disp { get; set; }

    public virtual SimNao DispNavigation { get; set; }

    public virtual ICollection<ItensVenda> ItensVenda { get; set; } = new List<ItensVenda>();

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}