// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trab_AV2.Model.Models;

public partial class SimNao
{
    public int Id { get; set; }

    public string Descricao { get; set; }

    public virtual ICollection<Produto> Produtos { get; set; } = new List<Produto>();
}