// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trab_AV2.Model.Models;

public partial class VwEstoque
{
    public string NmProduto { get; set; }

    public int Id { get; set; }

    public string Qtd { get; set; }

    public decimal Valor { get; set; }
}