// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trab_AV2.Model.Models;

public partial class VwEstoque
{
    public string ProDescricao { get; set; }

    public int Procodigo { get; set; }

    public decimal? Quantidade { get; set; }

    public decimal Valorvenda { get; set; }
}